---
- id: graylint
  name: graylint
  description: >-
    Run Ruff and omit previously existing errors on unmodified lines
  entry: "graylint -r :PRE-COMMIT: --lint 'ruff check'"
  language: python
  language_version: python3
  require_serial: true
  types: [python]
