---
name: darker-black-isort

on: push  # yamllint disable-line rule:truthy

jobs:
  reformat-modified:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Reformat code using the Darker GitHub action
        uses: akaihola/darker@1.7.3
        with:
          options: --check --diff --color --isort
          src: action release_tools setup.py src/graylint
          revision: origin/main...
