---
name: help-in-readme
on: [push]  # yamllint disable-line rule:truthy
jobs:
  help-in-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install '.'
      - name: Verify that README contains output of graylint --help
        shell: python
        run: |
          import sys
          from pathlib import Path
          from pprint import pprint
          from subprocess import check_output, STDOUT
          cmd = ["graylint", "--options-for-readme"]
          usage = check_output(cmd, stderr=STDOUT, encoding="utf-8")
          readme = Path("README.rst").read_text()
          if usage in readme:
              sys.exit(0)
          pprint(str.splitlines(usage, keepends=True), width=94)
          sys.exit(1)
